[package]
name = "esstra-rustc"
version = "0.1.0"
edition = "2018"

[dependencies]
esstra-lib = { path = "../esstra-lib" }
file-lock = "2.1.11"
log = "0.4.28"
nix = { version = "0.30.1", features = ["process"] }
serde_json = "1.0.143"
